const API=window.GENESIS_API_URL||"http://localhost:8080";
const projectId=localStorage.getItem("genesis_project_id")||"default-web";
const tokenKey="genesis_session_token";
localStorage.setItem("genesis_project_id",projectId);
const state=document.getElementById("sessionState");
const authPanel=document.getElementById("authPanel");
const output=document.createElement("div");output.className="result chat-log";document.querySelector("section").prepend(output);
function token(){return localStorage.getItem(tokenKey)||"";}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const t=token();if(t)headers.Authorization="Bearer "+t;const r=await fetch(API+path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
function setLoggedIn(user){state.textContent="● "+(user?.display_name||user?.email||"حساب متصل");authPanel.style.display="none";}
async function restore(){if(!token())return;try{const d=await api("/v1/auth/me");setLoggedIn(d.user);}catch{localStorage.removeItem(tokenKey);}}
async function auth(mode){const email=document.getElementById("authEmail").value.trim(),password=document.getElementById("authPassword").value,name=document.getElementById("authName").value.trim();if(!email||!password)throw new Error("أدخل البريد وكلمة المرور");const d=await api("/v1/auth/"+mode,{method:"POST",body:JSON.stringify({email,password,displayName:name||undefined})});localStorage.setItem(tokenKey,d.token);setLoggedIn(d.user);output.textContent="✅ تم الاتصال بـ Genesis AI.";}
document.getElementById("loginBtn").onclick=()=>auth("login").catch(e=>output.textContent="❌ "+e.message);
document.getElementById("signupBtn").onclick=()=>auth("signup").catch(e=>output.textContent="❌ "+e.message);
const send=document.querySelector(".composer button"),box=document.querySelector("textarea");
function addMessage(role,text){const el=document.createElement("div");el.className="msg "+role;el.textContent=text;output.appendChild(el);output.scrollTop=output.scrollHeight;}
async function sendTask(){const message=box.value.trim();if(!message)return;if(!token()){output.textContent="🔐 سجّل الدخول أولًا.";return;}addMessage("user",message);box.value="";const thinking=document.createElement("div");thinking.className="msg assistant";thinking.textContent="⏳ Genesis يعمل...";output.appendChild(thinking);try{const data=await api("/v1/chat/completions",{method:"POST",body:JSON.stringify({model:"auto",messages:[{role:"user",content:message}],projectId})});thinking.textContent=data.text||"تم التنفيذ.";}catch(e){thinking.textContent="❌ "+e.message;}}
send.addEventListener("click",sendTask);box.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendTask();}});
const integration=document.getElementById("integrations");if(integration)integration.addEventListener("click",async()=>{try{const d=await api("/v1/connectors");output.textContent="🔌 "+(d.connectors||[]).map(x=>x.platform||x.id).join(" • ");}catch(e){output.textContent="❌ "+e.message;}});
async function requestLinkedAccount(platformId,scopes,reason){const req=await api("/v1/account-access/request",{method:"POST",body:JSON.stringify({projectId,platformId,mode:"linked_browser",scopes,reason})});if(!confirm("Genesis يطلب إذنك للوصول إلى "+platformId+" ضمن: "+scopes.join(", ")+"\\n\\nهل توافق؟"))return req;return api("/v1/account-access/approve",{method:"POST",body:JSON.stringify({requestId:req.id})});}
window.GenesisAccount={requestLinkedAccount,projectId};restore();
const selfImprove=document.getElementById("selfImproveBtn");
if(selfImprove)selfImprove.onclick=async()=>{if(!token()){output.textContent="🔐 سجّل الدخول أولًا.";return;}const objective=prompt("ما الذي تريد أن يطوره Genesis في نفسه؟","حسّن الاعتمادية، الاختبارات، الأدوات، وسير التطوير الذاتي");if(!objective)return;selfImprove.disabled=true;output.textContent="🧠 بدأ Genesis دورة التطوير الذاتي...";try{const d=await api("/v1/self-development/run",{method:"POST",body:JSON.stringify({objective,mode:"self-improve",maxIterations:8,createPullRequest:true})});output.textContent="✅ اكتملت الدورة: "+JSON.stringify(d,null,2);}catch(e){output.textContent="❌ "+e.message;}finally{selfImprove.disabled=false;}};
const uiBtn=document.getElementById("uiDesignerBtn");
if(uiBtn)uiBtn.onclick=()=>{output.innerHTML='<div class="designer"><h3>🎨 UI Designer</h3><input id="screenName" placeholder="اسم الشاشة" value="Home"><textarea id="components" placeholder="Button,Card,TextField,Navigation">Header,Hero,Card,TextField,Button,Navigation</textarea><button id="makeSpec">إنشاء مواصفة الشاشة</button><pre id="specOut"></pre></div>';document.getElementById("makeSpec").onclick=async()=>{try{const name=document.getElementById("screenName").value||"Home";const components=document.getElementById("components").value.split(",").map(x=>x.trim()).filter(Boolean);const d=await api("/v1/ui/screen",{method:"POST",body:JSON.stringify({name,components})});document.getElementById("specOut").textContent=JSON.stringify(d,null,2);}catch(e){document.getElementById("specOut").textContent="❌ "+e.message;}};};
