import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
void main()=>runApp(const GenesisApp());
class GenesisApp extends StatelessWidget{const GenesisApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Genesis AI',theme:ThemeData(brightness:Brightness.dark,useMaterial3:true),home:const GenesisHome());}
class GenesisHome extends StatefulWidget{const GenesisHome({super.key});@override State<GenesisHome> createState()=>_GenesisHomeState();}
class _GenesisHomeState extends State<GenesisHome>{
 final input=TextEditingController(); final email=TextEditingController(); final password=TextEditingController(); final messages=<Map<String,String>>[];
 String base=const String.fromEnvironment('GENESIS_API_URL',defaultValue:''); String token=''; String conversationId=''; String model='auto'; List<dynamic> models=[]; bool loading=false;
 Future<dynamic> api(String path,{String method='GET',Map<String,dynamic>? body})async{final h=<String,String>{'Content-Type':'application/json',if(token.isNotEmpty)'Authorization':'Bearer $token'};final r=await http.request(Uri.parse(base+path),method:method,headers:h,body:body==null?null:jsonEncode(body));final d=r.body.isEmpty?{}:jsonDecode(r.body);if(r.statusCode>=400)throw Exception(d['error']??'Request failed');return d;}
 Future<void> login()async{try{final d=await api('/v1/auth/login',method:'POST',body:{'email':email.text,'password':password.text});setState((){token=d['token']??'';});await loadModels();}catch(e){_snack(e.toString());}}
 Future<void> loadModels()async{if(token.isEmpty)return;try{final d=await api('/v1/models/catalog');setState((){models=d['models']??[];});}catch(e){_snack(e.toString());}}
 Future<void> send()async{final text=input.text.trim();if(text.isEmpty||token.isEmpty||base.isEmpty)return;setState((){messages.add({'role':'user','content':text});input.clear();loading=true;});try{final d=await api('/v1/chat/completions',method:'POST',body:{'model':model,'messages':[{'role':'user','content':text}],'conversationId':conversationId.isEmpty?null:conversationId});setState((){conversationId=d['conversationId']??conversationId;messages.add({'role':'assistant','content':d['text']??''});loading=false;});}catch(e){setState((){loading=false;});_snack(e.toString());}}
 void _snack(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s))); }
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Genesis AI'),actions:[DropdownButton<String>(value:model,items:[const DropdownMenuItem(value:'auto',child:Text('Auto')), ...models.map((m)=>DropdownMenuItem(value:m['id'].toString(),child:Text(m['name']?.toString()??m['id'].toString())))],onChanged:(v){if(v!=null)setState(()=>model=v);})]),drawer:Drawer(child:ListView(children:[const DrawerHeader(child:Text('Genesis AI',style:TextStyle(fontSize:28))),for(final item in ['Chat','Projects','AI Studio','Files','Source Code','UI Designer','Integrations','Build','Testing','Logs','Releases','Credentials','Settings'])ListTile(title:Text(item),onTap:()=>Navigator.pop(context))])),body:Column(children:[if(token.isEmpty)Padding(padding:const EdgeInsets.all(12),child:Column(children:[TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password')),FilledButton(onPressed:login,child:const Text('Login'))])),Expanded(child:ListView(children:messages.map((m)=>ListTile(title:Text(m['role']==='user'?'أنت':'Genesis AI'),subtitle:Text(m['content']??''))).toList())),Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:input,enabled:token.isNotEmpty,decoration:const InputDecoration(hintText:'اكتب طلبك...'))),IconButton(onPressed:loading?null:send,icon:const Icon(Icons.send))]))]));}