import { chatExtended } from "./extended-providers.js";
type Change={path:string;content:string};
function token(){const t=process.env.GITHUB_TOKEN;if(!t)throw new Error("GITHUB_TOKEN is not configured");return t;}
async function gh(path:string,init:RequestInit={}){const r=await fetch("https://api.github.com"+path,{...init,headers:{Accept:"application/vnd.github+json",Authorization:"Bearer "+token(),"X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(init.headers??{})}});const text=await r.text();const data=text?JSON.parse(text):{};if(!r.ok)throw new Error("GitHub API "+r.status+": "+JSON.stringify(data).slice(0,1200));return data;}
export async function readRepository(repo:string,ref="main"){const tree=await gh("/repos/"+repo+"/git/trees/"+encodeURIComponent(ref)+"?recursive=1");const files=(tree.tree??[]).filter((x:any)=>x.type==="blob"&&x.size<=200000).slice(0,250);const out:Array<{path:string;content:string}>=[];for(const f of files){const d=await gh("/repos/"+repo+"/contents/"+f.path+"?ref="+encodeURIComponent(ref));out.push({path:f.path,content:Buffer.from(d.content??"","base64").toString("utf8")});}return out;}
async function currentSha(repo:string,path:string,ref:string){const d=await gh("/repos/"+repo+"/contents/"+path+"?ref="+encodeURIComponent(ref));return d.sha as string;}
async function branch(repo:string,name:string,base:string){const b=await gh("/repos/"+repo+"/git/ref/heads/"+encodeURIComponent(base));await gh("/repos/"+repo+"/git/refs",{method:"POST",body:JSON.stringify({ref:"refs/heads/"+name,sha:b.object.sha})});}
async function writeFile(repo:string,path:string,content:string,branchName:string,message:string){const sha=await currentSha(repo,path,branchName).catch(()=>undefined);await gh("/repos/"+repo+"/contents/"+path,{method:"PUT",body:JSON.stringify({message,content:Buffer.from(content).toString("base64"),branch:branchName,...(sha?{sha}:{})})});}
async function dispatchChecks(repo:string,branchName:string){await gh("/repos/"+repo+"/actions/workflows/genesis-agent.yml/dispatches",{method:"POST",body:JSON.stringify({ref:branchName,inputs:{task:"verify"}})});return Date.now();}
async function waitForChecks(repo:string,branchName:string,started:number,timeoutMs=180000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const d=await gh("/repos/"+repo+"/actions/runs?branch="+encodeURIComponent(branchName)+"&per_page=10");const run=(d.workflow_runs??[]).find((x:any)=>x.name==="Genesis Agent Checks"&&new Date(x.created_at).getTime()>=started-5000);if(run&&run.status==="completed")return {status:run.status,conclusion:run.conclusion,runId:run.id,url:run.html_url};await new Promise(r=>setTimeout(r,5000));}return {status:"timeout"};}
async function createPR(repo:string,branchName:string,base:string,title:string,body:string){return gh("/repos/"+repo+"/pulls",{method:"POST",body:JSON.stringify({title,head:branchName,base,body,draft:true})});}
function extractJson(text:string){const m=text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);const raw=(m?.[1]??text).trim();const s=raw.indexOf("{"),e=raw.lastIndexOf("}");if(s<0||e<s)throw new Error("Coding agent returned no JSON");return JSON.parse(raw.slice(s,e+1));}
export async function executeCodingTask(input:{repo?:string;objective:string;base?:string;createPullRequest?:boolean;maxFiles?:number;model?:string}){const target=input.repo??"ly7902800-coder/A";const base=input.base??"main";const files=await readRepository(target,base);const snapshot=files.map(f=>"FILE: "+f.path+"\n"+f.content.slice(0,12000)).join("\n\n");const model=input.model??"anthropic/claude-opus-5-5";const prompt="You are Genesis Coding Agent. Return strict JSON only: {\"summary\":\"...\",\"changes\":[{\"path\":\"...\",\"content\":\"complete file content\"}]}. Objective: "+input.objective+"\nRepository:\n"+snapshot;const plan=extractJson((await chatExtended({model,messages:[{role:"user",content:prompt}],maxTokens:120000})).text);const changes=(Array.isArray(plan.changes)?plan.changes:[]).slice(0,input.maxFiles??20) as Change[];if(!changes.length)throw new Error("No changes proposed");const branchName="genesis/agent-"+Date.now().toString(36);await branch(target,branchName,base);for(const c of changes)await writeFile(target,c.path,c.content,branchName,"feat(agent): "+String(plan.summary??"automated coding change").slice(0,72));const started=await dispatchChecks(target,branchName);const checks=await waitForChecks(target,branchName,started);let pullRequest:any=undefined;if(input.createPullRequest!==false&&checks.conclusion==="success"){const pr=await createPR(target,branchName,base,"Genesis Agent: "+String(plan.summary??input.objective).slice(0,90),"Automated Genesis Coding Agent change. Objective: "+input.objective);pullRequest={number:pr.number,url:pr.html_url};}return {branch:branchName,changedFiles:changes.map(c=>c.path),checks,pullRequest};}