import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createAiGateway } from "@genesis-ai/ai-gateway";
import { rateLimit, clientKey } from "./security.js";
import { initDatabase, dbHealth } from "./database/db.js";

const oauthProjects = new Map<string,{projectId:string;platform:"github"|"cloudflare"|"figma"|"google"}>();
const port=Number(process.env.PORT??8080);
const gateway=createAiGateway();
function sendJson(response:ServerResponse,status:number,data:unknown){response.statusCode=status;response.setHeader("Content-Type","application/json; charset=utf-8");response.end(JSON.stringify(data));}
async function readJson(request:IncomingMessage){let body="";for await(const chunk of request){body+=chunk;if(body.length>1_000_000)throw new Error("Request body too large");}return body?JSON.parse(body):{};}

const server=createServer(async(request,response)=>{
 try{
  const url=new URL(request.url??"/","http://localhost");
  if(!rateLimit(clientKey(request)))return sendJson(response,429,{error:"Too many requests"});
  if(url.pathname==="/health"&&request.method==="GET"){const database=await dbHealth();return sendJson(response,200,{ok:true,service:"genesis-api",database});}
  if(url.pathname==="/v1/google/gemini"&&request.method==="POST"){const b=await readJson(request);if(typeof b.input!=="string"||!b.input.trim())return sendJson(response,400,{error:"input is required"});const{geminiInteraction}=await import("@genesis-ai/ai-gateway/google-tools");return sendJson(response,200,await geminiInteraction(b.input,typeof b.model==="string"?b.model:"gemini-3.8-flash"));}
  if(url.pathname==="/v1/google/stitch/tool"&&request.method==="POST"){const b=await readJson(request);if(typeof b.tool!=="string"||!b.tool.trim())return sendJson(response,400,{error:"tool is required"});const{stitchCallTool}=await import("@genesis-ai/ai-gateway/google-tools");return sendJson(response,200,await stitchCallTool(b.tool,b.args&&typeof b.args==="object"?b.args:{}));}
  if(url.pathname==="/v1/google/notebook"&&request.method==="POST"){const b=await readJson(request);const{createGeminiNotebook,listGeminiNotebooks,addGeminiNotebookSource}=await import("@genesis-ai/ai-gateway/google-tools");if(b.action==="list")return sendJson(response,200,await listGeminiNotebooks());if(b.action==="create"&&typeof b.title==="string")return sendJson(response,200,await createGeminiNotebook(b.title));if(b.action==="add_source"&&typeof b.notebookId==="string"&&b.source&&typeof b.source==="object")return sendJson(response,200,await addGeminiNotebookSource(b.notebookId,b.source));return sendJson(response,400,{error:"action must be list, create, or add_source with the required fields"});}
  if(url.pathname==="/v1/providers"&&request.method==="GET")return sendJson(response,200,{providers:gateway.listProviders()});
  if(url.pathname==="/v1/models"&&request.method==="GET")return sendJson(response,200,{models:gateway.listModels()});
  if(url.pathname==="/v1/models/live"&&request.method==="GET")return sendJson(response,200,await gateway.discoverModels());
  if(url.pathname==="/v1/tools"&&request.method==="GET")return sendJson(response,200,{tools:gateway.listTools()});
  if(url.pathname==="/v1/features"&&request.method==="GET"){const[{GENESIS_FEATURES},{ADDITIONAL_GENESIS_FEATURES}]=await Promise.all([import("@genesis-ai/ai-gateway/feature-registry"),import("@genesis-ai/ai-gateway/additional-features")]);return sendJson(response,200,{features:[...GENESIS_FEATURES,...ADDITIONAL_GENESIS_FEATURES]});}
  if(url.pathname==="/v1/connectors"&&request.method==="GET")return sendJson(response,200,{connectors:[...gateway.listOAuthPlatforms(),...gateway.listConnectors()]});
  if(url.pathname==="/v1/platforms"&&request.method==="GET")return sendJson(response,200,{platforms:gateway.listPlatformTargets()});
  if(url.pathname==="/v1/platform/discover"&&request.method==="POST"){const b=await readJson(request);if(typeof b.platform!=="string")return sendJson(response,400,{error:"platform is required"});const p=gateway.discoverPlatform(b.platform);return p?sendJson(response,200,{platform:p}):sendJson(response,404,{error:"Platform not found"});}
  if(url.pathname==="/v1/platform/plan"&&request.method==="POST"){const b=await readJson(request);if(typeof b.platform!=="string"||typeof b.objective!=="string")return sendJson(response,400,{error:"platform and objective are required"});const p=gateway.discoverPlatform(b.platform);if(!p)return sendJson(response,404,{error:"Platform not found"});return sendJson(response,200,{plan:gateway.planPlatformMission(b.objective,p)});}
  if(url.pathname==="/v1/platform/execute"&&request.method==="POST"){const b=await readJson(request);if(!b.mission)return sendJson(response,400,{error:"mission is required"});return sendJson(response,200,await gateway.executePlatformMission(b.mission,b.approved===true));}
  if(url.pathname==="/v1/connector/action"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId||!b.platformId||!b.action)return sendJson(response,400,{error:"projectId, platformId and action are required"});return sendJson(response,200,await gateway.executeConnectorAction({projectId:b.projectId,platformId:b.platformId,action:b.action,input:b.input,approved:b.approved===true}));}
  if(url.pathname==="/v1/account-access/request"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId||!b.platformId||!Array.isArray(b.scopes))return sendJson(response,400,{error:"projectId, platformId and scopes are required"});return sendJson(response,201,gateway.requestAccountAccess({projectId:b.projectId,platformId:b.platformId,mode:b.mode==="oauth"||b.mode==="api"||b.mode==="linked_browser"?b.mode:"linked_browser",scopes:b.scopes,reason:typeof b.reason==="string"?b.reason:"Genesis needs access to this connected platform."}));}
  if(url.pathname==="/v1/account-access"&&request.method==="GET")return sendJson(response,200,{requests:gateway.listAccountAccess(url.searchParams.get("projectId")??undefined)});
  if(url.pathname==="/v1/account-access/approve"&&request.method==="POST"){const b=await readJson(request);if(!b.requestId)return sendJson(response,400,{error:"requestId is required"});return sendJson(response,200,{request:gateway.approveAccountAccess(b.requestId)});}
  if(url.pathname==="/v1/account-access/revoke"&&request.method==="POST"){const b=await readJson(request);if(!b.requestId)return sendJson(response,400,{error:"requestId is required"});return sendJson(response,200,{revoked:gateway.revokeAccountAccess(b.requestId)});}
  if(url.pathname==="/v1/account-access/linked-browser"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId||!b.platformId)return sendJson(response,400,{error:"projectId and platformId are required"});return sendJson(response,201,{session:gateway.createLinkedBrowserSession(b.projectId,b.platformId,b.ttlMinutes)});}
  if(url.pathname==="/v1/account-access/linked-browser/approve"&&request.method==="POST"){const b=await readJson(request);if(!b.sessionId)return sendJson(response,400,{error:"sessionId is required"});return sendJson(response,200,{session:gateway.approveLinkedBrowserSession(b.sessionId)});}
  if(url.pathname==="/v1/account-access/linked-browser/revoke"&&request.method==="POST"){const b=await readJson(request);if(!b.sessionId)return sendJson(response,400,{error:"sessionId is required"});return sendJson(response,200,{revoked:gateway.revokeLinkedBrowserSession(b.sessionId)});}
  if(url.pathname==="/v1/browser/session"&&request.method==="POST"){const b=await readJson(request);if(typeof b.platform!=="string"||!Array.isArray(b.actions))return sendJson(response,400,{error:"platform and actions are required"});return sendJson(response,201,{session:gateway.createBrowserSession(b.platform,b.actions),policy:gateway.browserPolicy(b.actions)});}
  if(url.pathname==="/v1/browser/interact"&&request.method==="POST"){const b=await readJson(request);if(!process.env.FIRECRAWL_API_KEY)return sendJson(response,503,{error:"Browser agent is not configured. Set FIRECRAWL_API_KEY on the server."});if(typeof b.url!=="string"||typeof b.prompt!=="string")return sendJson(response,400,{error:"url and prompt are required"});const upstream=await fetch("https://api.firecrawl.dev/v2/browser",{method:"POST",headers:{"Authorization":`Bearer ${process.env.FIRECRAWL_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({url:b.url,prompt:b.prompt})});const text=await upstream.text();let data:unknown;try{data=JSON.parse(text)}catch{data={raw:text}}return sendJson(response,upstream.status,data);}

  if(url.pathname==="/v1/account/google"&&request.method==="GET"){const projectId=url.searchParams.get("projectId");if(!projectId)return sendJson(response,400,{error:"projectId is required"});const connector=gateway.listOAuthPlatforms().find(x=>x.platform==="google");return sendJson(response,200,{platform:"google",projectId,connected:false,configured:connector?.configured??false,status:"not_connected",scopes:connector?.scopes??[],capabilities:{profile:true,drive:true,calendar:true,gmail:true,contacts:true,docs:true,sheets:true,slides:true,youtube:true}});}
  if(url.pathname==="/v1/account/google/connect"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId||!b.redirectUri)return sendJson(response,400,{error:"projectId and redirectUri are required"});const start=gateway.startOAuth("google",b.redirectUri);oauthProjects.set(start.state,{projectId:b.projectId,platform:"google"});return sendJson(response,200,{provider:"google",projectId:b.projectId,authorizationUrl:start.authorizationUrl,state:start.state,permissions:gateway.listOAuthPlatforms().find(x=>x.platform==="google")?.scopes??[]});}
  if(url.pathname==="/v1/connectors/authorize"&&request.method==="POST"){const b=await readJson(request);if(!b.platform||!b.projectId||!b.redirectUri)return sendJson(response,400,{error:"platform, projectId and redirectUri are required"});const start=gateway.startOAuth(b.platform,b.redirectUri);oauthProjects.set(start.state,{projectId:b.projectId,platform:b.platform});return sendJson(response,200,{platform:b.platform,authorizationUrl:start.authorizationUrl,state:start.state});}
  if(url.pathname==="/v1/connectors/callback"&&request.method==="GET"){const code=url.searchParams.get("code"),state=url.searchParams.get("state");const redirectUri=url.searchParams.get("redirect_uri")??process.env.GENESIS_OAUTH_CALLBACK_URL??"";if(!code||!state||!redirectUri)return sendJson(response,400,{error:"code, state and redirect URI are required"});const target=oauthProjects.get(state);if(!target)return sendJson(response,400,{error:"Unknown or expired OAuth state"});const token=await gateway.finishOAuth(target.platform,code,state,redirectUri);oauthProjects.delete(state);const{storeConnectorTokens}=await import("@genesis-ai/ai-gateway/token-vault");const ref=storeConnectorTokens({accessToken:token.accessToken,refreshToken:token.refreshToken,expiresAt:token.expiresIn?Date.now()+token.expiresIn*1000:undefined});gateway.approvePlatformAccess(target.projectId,target.platform);const{attachConnectorCredentials}=await import("@genesis-ai/ai-gateway/platform-permissions");attachConnectorCredentials(target.projectId,target.platform,{accessTokenRef:ref,expiresAt:token.expiresIn?Date.now()+token.expiresIn*1000:undefined});return sendJson(response,200,{connected:true,platform:target.platform,projectId:target.projectId,scopes:token.scope?.split(/[ ,]/).filter(Boolean)});}
  if(url.pathname==="/v1/account/google/disconnect"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId)return sendJson(response,400,{error:"projectId is required"});return sendJson(response,200,{disconnected:gateway.revokePlatformAccess(b.projectId,"google"),platform:"google"});}

  if(url.pathname==="/v1/mission"&&request.method==="POST"){const b=await readJson(request);if(typeof b.objective!=="string"||!b.objective.trim())return sendJson(response,400,{error:"objective is required"});return sendJson(response,201,gateway.createBrainPlan(b.objective));}
  if(url.pathname==="/v1/missions"&&request.method==="GET")return sendJson(response,200,{missions:gateway.listMissions()});
  const mm=url.pathname.match(/^\/v1\/missions\/([^/]+)$/);if(mm&&request.method==="GET"){const m=gateway.getMission(mm[1]);return m?sendJson(response,200,{mission:m}):sendJson(response,404,{error:"Mission not found"});}
  const ms=url.pathname.match(/^\/v1\/missions\/([^/]+)\/steps\/([^/]+)$/);if(ms&&request.method==="POST"){const b=await readJson(request);const allowed=["pending","running","completed","failed","blocked","approval_required"];if(!allowed.includes(b.status))return sendJson(response,400,{error:"invalid step status"});const m=gateway.updateMissionStep(ms[1],ms[2],b.status);return m?sendJson(response,200,{mission:m}):sendJson(response,404,{error:"Mission or step not found"});}
  if(url.pathname==="/v1/project/dna"&&request.method==="GET"){const id=url.searchParams.get("projectId");if(!id)return sendJson(response,400,{error:"projectId is required"});return sendJson(response,200,{dna:gateway.getProjectDNA(id)??null});}
  if(url.pathname==="/v1/project/dna"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId)return sendJson(response,400,{error:"projectId is required"});return sendJson(response,200,{dna:gateway.upsertProjectDNA({projectId:b.projectId,name:b.name,type:b.type,stack:Array.isArray(b.stack)?b.stack:[],integrations:Array.isArray(b.integrations)?b.integrations:[],requirements:Array.isArray(b.requirements)?b.requirements:[],decisions:Array.isArray(b.decisions)?b.decisions:[],knownIssues:Array.isArray(b.knownIssues)?b.knownIssues:[]})});}
  if(url.pathname==="/v1/project/checkpoints"&&request.method==="GET"){const id=url.searchParams.get("projectId");if(!id)return sendJson(response,400,{error:"projectId is required"});return sendJson(response,200,{checkpoints:gateway.listCheckpoints(id),latest:gateway.latestCheckpoint(id)??null});}
  if(url.pathname==="/v1/project/checkpoints"&&request.method==="POST"){const b=await readJson(request);if(!b.projectId||!b.label)return sendJson(response,400,{error:"projectId and label are required"});return sendJson(response,201,{checkpoint:gateway.createCheckpoint(b.projectId,b.label,b.snapshotRef)});}
  if(url.pathname==="/v1/self-healing/plan"&&request.method==="POST"){const b=await readJson(request);if(typeof b.error!=="string"||!b.error.trim())return sendJson(response,400,{error:"error is required"});return sendJson(response,200,{plan:gateway.createHealingPlan(b.error)});}
  if(url.pathname==="/v1/agents/parallel-plan"&&request.method==="POST"){const b=await readJson(request);if(typeof b.objective!=="string"||!b.objective.trim())return sendJson(response,400,{error:"objective is required"});return sendJson(response,200,{tasks:gateway.planParallelAgents(b.objective)});}
  if(url.pathname==="/v1/platform/access/request"&&request.method==="POST"){const b=await readJson(request);if(!b.platformId||!b.projectId||!Array.isArray(b.scopes))return sendJson(response,400,{error:"platformId, projectId and scopes are required"});return sendJson(response,200,gateway.requestPlatformAccess({platformId:b.platformId,projectId:b.projectId,scopes:b.scopes,reason:typeof b.reason==="string"?b.reason:"Genesis needs to work on the selected platform."}));}
  if(url.pathname==="/v1/platform/access/approve"&&request.method==="POST"){const b=await readJson(request);if(!b.platformId||!b.projectId)return sendJson(response,400,{error:"platformId and projectId are required"});return sendJson(response,200,gateway.approvePlatformAccess(b.projectId,b.platformId));}
  if(url.pathname==="/v1/platform/access/revoke"&&request.method==="POST"){const b=await readJson(request);return sendJson(response,200,{revoked:gateway.revokePlatformAccess(b.projectId,b.platformId)});}
  if(url.pathname==="/v1/tools/execute"&&request.method==="POST"){const b=await readJson(request);if(typeof b.name!=="string")return sendJson(response,400,{error:"tool name is required"});return sendJson(response,200,await gateway.executeTool(b.name,b.input));}
  if(url.pathname==="/v1/approvals"&&request.method==="GET")return sendJson(response,200,{approvals:gateway.listApprovals()});
  const am=url.pathname.match(/^\/v1\/approvals\/([^/]+)\/(approve|reject)$/);if(am&&request.method==="POST")return sendJson(response,200,gateway.decideApproval(am[1],am[2]==="approve"));
  if(url.pathname==="/v1/research"&&request.method==="POST"){const b=await readJson(request);if(typeof b.query!=="string"||!b.query.trim())return sendJson(response,400,{error:"query is required"});return sendJson(response,200,await gateway.research(b.query,b.limit));}
  if(url.pathname==="/v1/chat/completions"&&request.method==="POST")return sendJson(response,200,await gateway.chat(await readJson(request)));
  return sendJson(response,404,{error:"Not found"});
 }catch(error){return sendJson(response,500,{error:error instanceof Error?error.message:"Internal server error"});}
});
server.listen(port,async()=>{try{const enabled=await initDatabase();console.log(`Genesis API listening on :${port} database=${enabled?"connected":"not-configured"}`);}catch(error){console.error("Database initialization failed:",error);process.exitCode=1;}});
