import { getDatabase } from "./database/db.js";

export async function saveMission(userId:string,projectId:string|undefined,mission:any){const db=getDatabase();if(!db)throw new Error("Database is not configured");await db.query("INSERT INTO missions(id,project_id,owner_id,objective,status,risk_level,approval_required) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING",[mission.id,projectId??null,userId,mission.objective,mission.status,"low",mission.steps.some((s:any)=>s.status==="approval_required")]);for(let i=0;i<mission.steps.length;i++){const s=mission.steps[i];await db.query("INSERT INTO mission_steps(mission_id,step_key,title,kind,status,position,input) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(mission_id,step_key) DO NOTHING",[mission.id,s.id,s.name,s.agent,s.status,i,{dependsOn:s.dependsOn,description:s.description}]);}return mission;}
export async function listPersistedMissions(userId:string){const db=getDatabase();if(!db)return [];const r=await db.query("SELECT * FROM missions WHERE owner_id=$1 ORDER BY created_at DESC LIMIT 100",[userId]);return r.rows;}
export async function saveMemory(userId:string,projectId:string|undefined,kind:string,content:string,importance=0.5){const db=getDatabase();if(!db)throw new Error("Database is not configured");const r=await db.query("INSERT INTO memories(user_id,project_id,kind,content,importance) VALUES($1,$2,$3,$4,$5) RETURNING *",[userId,projectId??null,kind,content,importance]);return r.rows[0];}
export async function listPersistedMemories(userId:string,projectId?:string){const db=getDatabase();if(!db)return [];const r=projectId?await db.query("SELECT * FROM memories WHERE user_id=$1 AND project_id=$2 ORDER BY importance DESC,created_at DESC LIMIT 200",[userId,projectId]):await db.query("SELECT * FROM memories WHERE user_id=$1 ORDER BY importance DESC,created_at DESC LIMIT 200",[userId]);return r.rows;}
export async function deletePersistedMemory(userId:string,id:string){const db=getDatabase();if(!db)return false;const r=await db.query("DELETE FROM memories WHERE id=$1 AND user_id=$2",[id,userId]);return (r.rowCount??0)>0;}
export async function createChat(userId:string,projectId?:string,title?:string){const db=getDatabase();if(!db)throw new Error("Database is not configured");const r=await db.query("INSERT INTO chats(user_id,project_id,title) VALUES($1,$2,$3) RETURNING id,title,project_id,created_at,updated_at",[userId,projectId??null,title??"Genesis Chat"]);return r.rows[0];}
export async function appendChatMessages(userId:string,chatId:string,messages:any[]){const db=getDatabase();if(!db)throw new Error("Database is not configured");const owner=await db.query("SELECT id FROM chats WHERE id=$1 AND user_id=$2",[chatId,userId]);if(!owner.rowCount)throw new Error("Chat not found");for(const m of messages){if(!m||!["system","user","assistant"].includes(m.role)||typeof m.content!=="string")continue;await db.query("INSERT INTO chat_messages(chat_id,role,content,model,provider,metadata) VALUES($1,$2,$3,$4,$5,$6)",[chatId,m.role,m.content,m.model??null,m.provider??null,m.metadata&&typeof m.metadata==="object"?m.metadata:{}]);}await db.query("UPDATE chats SET updated_at=now() WHERE id=$1",[chatId]);return chatId;}
export async function getChatMessages(userId:string,chatId:string){const db=getDatabase();if(!db)throw new Error("Database is not configured");const owner=await db.query("SELECT id,title,project_id,created_at,updated_at FROM chats WHERE id=$1 AND user_id=$2",[chatId,userId]);if(!owner.rowCount)throw new Error("Chat not found");const r=await db.query("SELECT id,role,content,model,provider,metadata,created_at FROM chat_messages WHERE chat_id=$1 ORDER BY created_at ASC,id ASC",[chatId]);return {chat:owner.rows[0],messages:r.rows};}
export async function saveChat(userId:string,projectId:string|undefined,messages:any[],title?:string){const chat=await createChat(userId,projectId,title??messages.find((m:any)=>m.role==="user")?.content?.slice(0,80)??"Genesis Chat");await appendChatMessages(userId,chat.id,messages);return chat.id;}
export async function getChats(userId:string){const db=getDatabase();if(!db)return [];const r=await db.query("SELECT id,title,project_id,created_at,updated_at FROM chats WHERE user_id=$1 ORDER BY updated_at DESC LIMIT 100",[userId]);return r.rows;}
